openapi: 3.0.1
info:
  title: Matie API with Swagger
  description: Matie 프로젝트의 swagger api 입니다.
  version: 0.1.0
servers:
- url: https://localhost:8085
tags: []
paths:
  /user:
    post:
      tags:
      - user
      summary: 회원가입 하기
      description: 회원가입할 수 있습니다.
      operationId: user-post
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/user372939519'
            examples:
              user-post:
                value: "{\r\n  \"name\" : \"nickname\",\r\n  \"userId\" : \"hyeseung22\"\
                  ,\r\n  \"email\" : \"peace10200khs@e-mirim.hs.kr1\",\r\n  \"pw\"\
                  \ : \"hyeseung2!\"\r\n}"
      responses:
        "201":
          description: "201"
components:
  schemas:
    user372939519:
      type: object
      properties:
        pw:
          type: string
          description: 사용자 비밀번호
        name:
          type: string
          description: 사용자 이름
        userId:
          type: string
          description: 사용자 아이디
        email:
          type: string
          description: 사용자 이메일
